spring:
  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: false
    validateOnMigrate: true
    cleanDisabled: true

logging:
  level:
    root: WARN
    org.hibernate: WARN

next:
  server:
    url: https://${NEXT_SERVER_HOST:coing}