name: Deploy To EC2

on:
  workflow_run:
    workflows: ["PR SpringBoot Test"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: AWS Resource에 접근할 수 있게 AWS credentials 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: ECR에 로그인하기
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker 이미지 생성
        working-directory: backend
        run: docker build -t coing-server .

      - name: Docker 이미지에 Tag 붙이기
        working-directory: backend
        run: docker tag coing-server ${{ steps.login-ecr.outputs.registry }}/coing-server:latest

      - name: ECR에 Docker 이미지 Push하기
        working-directory: backend
        run: docker push ${{ steps.login-ecr.outputs.registry }}/coing-server:latest

      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            docker stop coing-server || true
            docker rm coing-server || true
            docker pull ${{ steps.login-ecr.outputs.registry }}/coing-server:latest
            docker run -d --name coing-server -p 8080:8080 ${{ steps.login-ecr.outputs.registry }}/coing-server:latest
