name: Deploy To Vercel

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 23

      - name: api_schema.json 생성하기 위해 빌드
        working-directory: backend
        run: ./gradlew clean build
        env:
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          JWT_EXPIRE_SECONDS: ${{ secrets.JWT_EXPIRE_SECONDS }}
          JWT_REFRESH_EXPIRE_SECONDS: ${{ secrets.JWT_REFRESH_EXPIRE_SECONDS }}
          UPBIT_WS_URI: ${{ secrets.UPBIT_WS_URI }}
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}

      - name: Node.js 설치
        uses: actions/setup-node@v4
        with:
          node-version-file: "frontend/.nvmrc"

      - name: Dependencies 설치
        run: npm install

      - name: Doppler CLI 설치
        uses: dopplerhq/cli-action@v3

      - name: Doppler 설정
        run: |
          npm run doppler:setup
          doppler configure set config prd
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_FRONTEND_TOKEN }}

      - name: schema.d.ts 생성
        working-directory: frontend
        run: npm run codegen

      - name: .env 파일 다운로드
        working-directory: frontend
        run: npm run doppler

      - name: Vercel CLI 설치
        working-directory: frontend
        run: npm install -g vercel

      - name: Vercel에 배포
        working-directory: frontend
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
